spring:
  profile: local
  message: local environment

  application:
    name: locking-prototype

  flyway:
    baseline-on-migrate: true

  datasource:
    url: jdbc:postgresql://localhost:5433/order_db?currentSchema=order_schema
    platform: postgres
    username: appuser
    password: appuserpass
    driverClassName: org.postgresql.Driver
    initialize-mode: never
    xa:
      data-source-class-name: org.postgresql.xa.PGXADataSource
    tomcat:
      jmx-enabled: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        generate_statistics: false
        jdbc:
          batch_size: 10

springdoc:
  swagger-ui:
    path: /swagger-ui.html
