CREATE TABLE CUSTOMER
(
  CUSTOMER_NBR VARCHAR(20) NOT NULL,
  CUSTOMER_STUS_CD VARCHAR(20) NOT NULL,
  CUSTOMER_FILER_CD VARCHAR(3) NOT NULL,
  CUSTOMER_TOTL_AMT DECIMAL(15,2) NOT NULL,
  VERSION TIMESTAMP,
  CRTE_BY_ID VARCHAR(10) NOT NULL,
  UPD_BY_ID VARCHAR(10) NOT NULL,
  CRTE_TS TIMESTAMP,
  UPD_TS TIMESTAMP,
  CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_NBR)
);

CREATE TABLE C_ORDER
(
  ORDER_NBR VARCHAR(20),
  CUSTOMER_NBR VARCHAR(20),
  ENTRY_NBR VARCHAR(15),
  ENTRY_AMT DECIMAL(15,2) NOT NULL,
  CRTE_BY_ID VARCHAR(10) NOT NULL,
  VERSION TIMESTAMP,
  UPD_BY_ID VARCHAR(10) NOT NULL,
  CRTE_TS TIMESTAMP,
  UPD_TS TIMESTAMP,
  CONSTRAINT PK_CL_BILL_DETL PRIMARY KEY (ORDER_NBR)
);

ALTER TABLE C_ORDER ADD CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_NBR) REFERENCES CUSTOMER(CUSTOMER_NBR);

CREATE TABLE ORDER_EVENT
(
    EVENT_ID VARCHAR(34),
    OBJ_ID VARCHAR(20),
    ACTION_CD VARCHAR(10),
    VERSION TIMESTAMP,
    CRTE_BY_ID VARCHAR(10) NOT NULL,
    UPD_BY_ID VARCHAR(10) NOT NULL,
    CRTE_TS TIMESTAMP,
    UPD_TS TIMESTAMP,
    CONSTRAINT PK_CL_ORDER_EVENT PRIMARY KEY (EVENT_ID)
);

CREATE SEQUENCE ORDER_NBR_SEQ INCREMENT BY 1 START 1 MINVALUE 1 CACHE 1;

CREATE SEQUENCE CUSTOMER_NBR_SEQ INCREMENT BY 1 START 1 MINVALUE 1 CACHE 1;