CREATE TABLE CL_BILL
(
  BILL_NBR VARCHAR(20) NOT NULL,
  BILL_STUS_CD VARCHAR(20) NOT NULL,
  FILER_CD VARCHAR(3) NOT NULL,
  BILL_TOTL_AMT DECIMAL(15,2) NOT NULL,
  CRTE_BY_ID VARCHAR(10) NOT NULL,
  UPD_BY_ID VARCHAR(10) NOT NULL,
  CRTE_TS TIMESTAMP,
  UPD_TS TIMESTAMP,
  CONSTRAINT PK_CL_BILL PRIMARY KEY (BILL_NBR)
);

CREATE TABLE CL_BILL_DETL
(
  ENTRY_BILL_NBR VARCHAR(20),
  CL_BILL_NBR VARCHAR(20),
  ENTRY_NBR VARCHAR(15),
  ENTRY_AMT DECIMAL(15,2) NOT NULL,
  CRTE_BY_ID VARCHAR(10) NOT NULL,
  UPD_BY_ID VARCHAR(10) NOT NULL,
  CRTE_TS TIMESTAMP,
  UPD_TS TIMESTAMP,
  CONSTRAINT PK_CL_BILL_DETL PRIMARY KEY (ENTRY_BILL_NBR)
);

ALTER TABLE CL_BILL_DETL ADD CONSTRAINT FK_CL_BILL FOREIGN KEY (CL_BILL_NBR) REFERENCES CL_BILL(BILL_NBR);

CREATE TABLE CL_BILL_EVENT
(
    EVENT_ID VARCHAR(34),
    OBJ_ID VARCHAR(20),
    ACTION_CD VARCHAR(10),
    CRTE_BY_ID VARCHAR(10) NOT NULL,
    UPD_BY_ID VARCHAR(10) NOT NULL,
    CRTE_TS TIMESTAMP,
    UPD_TS TIMESTAMP,
    CONSTRAINT PK_CL_BILL_EVENT PRIMARY KEY (EVENT_ID)
);

CREATE SEQUENCE ENTRY_BILL_NBR_SEQ INCREMENT BY 1 START 1 MINVALUE 1 CACHE 1;

CREATE SEQUENCE BILL_NBR_SEQ INCREMENT BY 1 START 1 MINVALUE 1 CACHE 1;
